services:
  forsaj-backend:
    image: forsaj-backend:latest
    build:
      context: .
      dockerfile: Dockerfile.backend
    restart: unless-stopped
    environment:
      PORT: "3001"
      PUBLIC_BASE_URL: ""
      JWT_SECRET: "forsaj-secret-key-2026" # Change this in production
    volumes:
      - /datastore/forsaj/uploads:/app/uploads
      - /datastore/forsaj/json:/app/json
    networks:
      - edge
    labels:
      - 'traefik.enable=true'
      - 'traefik.docker.network=edge'
      - 'traefik.http.routers.forsaj-api.rule=(Host(`forsaj.octotech.az`) || Host(`forsaj.az`)) && (PathPrefix(`/api`) || PathPrefix(`/uploads`))'
      - 'traefik.http.routers.forsaj-api.entrypoints=web'
      - 'traefik.http.routers.forsaj-api.priority=100'
      - 'traefik.http.services.forsaj-api.loadbalancer.server.port=3001'

  forsaj-frontend:
    image: forsaj-frontend:latest
    build:
      context: .
      dockerfile: Dockerfile.frontend
    restart: unless-stopped
    networks:
      - edge
    labels:
      - 'traefik.enable=true'
      - 'traefik.docker.network=edge'
      - 'traefik.http.routers.forsaj.rule=Host(`forsaj.octotech.az`) || Host(`forsaj.az`)'
      - 'traefik.http.routers.forsaj.entrypoints=web'
      - 'traefik.http.services.forsaj.loadbalancer.server.port=80'

networks:
  edge:
    external: true
