services:
  forsaj-backend:
    image: forsaj-backend:latest
    restart: unless-stopped
    environment:
      PORT: "3001"
      PUBLIC_BASE_URL: ""
    volumes:
      - /datastore/forsaj-club-offroad-v3/uploads:/app/uploads
      - /datastore/forsaj-club-offroad-v3/json:/app/json
    networks:
      - edge
    labels:
      - 'traefik.enable=true'
      - 'traefik.docker.network=edge'
      - 'traefik.http.routers.forsaj-api.rule=(Host(`forsaj.local`) || Host(`forsaj-club.com`)) && (PathPrefix(`/api`) || PathPrefix(`/uploads`))'
      - 'traefik.http.routers.forsaj-api.entrypoints=web'
      - 'traefik.http.routers.forsaj-api.priority=100'
      - 'traefik.http.services.forsaj-api.loadbalancer.server.port=3001'

  forsaj-frontend:
    image: forsaj-frontend:latest
    restart: unless-stopped
    volumes:
      - /datastore/forsaj-club-offroad-v3/nginx-logs:/var/log/nginx
    networks:
      - edge
    labels:
      - 'traefik.enable=true'
      - 'traefik.docker.network=edge'
      - 'traefik.http.routers.forsaj.rule=Host(`forsaj.local`) || Host(`forsaj-club.com`)'
      - 'traefik.http.routers.forsaj.entrypoints=web'
      - 'traefik.http.services.forsaj.loadbalancer.server.port=80'

networks:
  edge:
    external: true
